export const AI_MODELS = [
  {
    id: "deepseek-ai/DeepSeek-V3.1",
    name: "DeepSeek V3.1",
    description: "Best reasoning, native tool use",
    pricing: "1.05 / 3.10 USDC per M tokens",
    speed: "~45s",
    stars: 5,
    use_case: "High-stakes disputes",
    tee: true,
    context: "128K",
    enabled: true,
  },
  {
    id: "anthropic/claude-sonnet-4-5",
    name: "Claude Sonnet 4.5",
    description: "Excellent tool use and reasoning",
    pricing: "3.00 / 15.50 USDC per M tokens",
    speed: "~15s",
    stars: 5,
    use_case: "Premium disputes",
    tee: false,
    context: "200K",
    enabled: true,
  },
  {
    id: "Qwen/Qwen3-30B-A3B-Instruct-2507",
    name: "Qwen3 30B",
    description: "Fast, cost-effective",
    pricing: "0.15 / 0.55 USDC per M tokens",
    speed: "~10s",
    stars: 3,
    use_case: "Standard disputes",
    tee: true,
    context: "262K",
    enabled: false,
  },
  {
    id: "openai/gpt-oss-120b",
    name: "GPT-OSS 120B",
    description: "Strong reasoning, tool use",
    pricing: "0.15 / 0.55 USDC per M tokens",
    speed: "~20s",
    stars: 4,
    use_case: "Complex disputes",
    tee: true,
    context: "131K",
    enabled: false,
  },
  {
    id: "zai-org/GLM-4.7",
    name: "GLM-4.7",
    description: "Hybrid reasoning",
    pricing: "0.85 / 3.30 USDC per M tokens",
    speed: "~25s",
    stars: 4,
    use_case: "Deep analysis",
    tee: true,
    context: "131K",
    enabled: false,
  },
  {
    id: "anthropic/claude-opus-4-6",
    name: "Claude Opus 4.6",
    description: "Most intelligent, best agents",
    pricing: "5.00 / 25.00 USDC per M tokens",
    speed: "~30s",
    stars: 5,
    use_case: "Highest-stakes disputes",
    tee: false,
    context: "200K",
    enabled: false,
  },
  {
    id: "google/gemini-3-pro",
    name: "Gemini 3 Pro",
    description: "Huge context window (1M tokens)",
    pricing: "1.25 / 15.00 USDC per M tokens",
    speed: "~20s",
    stars: 4,
    use_case: "Evidence-heavy disputes",
    tee: false,
    context: "1000K",
    enabled: false,
  },
  {
    id: "openai/gpt-5.2",
    name: "GPT-5.2",
    description: "Large context, good reasoning",
    pricing: "1.80 / 15.50 USDC per M tokens",
    speed: "~20s",
    stars: 4,
    use_case: "Complex disputes",
    tee: false,
    context: "400K",
    enabled: false,
  },
] as const;

export type ModelId = (typeof AI_MODELS)[number]["id"];
